// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoInterDisciplinar.Data;

#nullable disable

namespace ProjetoInterDisciplinar.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240427213928_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoInterDisciplinar.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<int>("HorasDeServico")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_FUNCIONARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Funcao = 2,
                            HorasDeServico = 8,
                            Nome = "Guilherme"
                        },
                        new
                        {
                            Id = 2,
                            Funcao = 6,
                            HorasDeServico = 8,
                            Nome = "Jessica"
                        },
                        new
                        {
                            Id = 3,
                            Funcao = 1,
                            HorasDeServico = 8,
                            Nome = "Leonardo"
                        },
                        new
                        {
                            Id = 4,
                            Funcao = 3,
                            HorasDeServico = 8,
                            Nome = "Lucas"
                        },
                        new
                        {
                            Id = 5,
                            Funcao = 4,
                            HorasDeServico = 8,
                            Nome = "Rogerio"
                        },
                        new
                        {
                            Id = 6,
                            Funcao = 5,
                            HorasDeServico = 8,
                            Nome = "Cleber Machado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
